/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.Books;
import com.example.jooq.tables.Borrowings;
import com.example.jooq.tables.Readers;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_BOOKS_AUTHOR = Internal.createIndex(DSL.name("idx_books_author"), Books.BOOKS, new OrderField[]{Books.BOOKS.AUTHOR_ID}, false);
    public static final Index IDX_BOOKS_GENRE = Internal.createIndex(DSL.name("idx_books_genre"), Books.BOOKS, new OrderField[]{Books.BOOKS.GENRE_ID}, false);
    public static final Index IDX_BORROWINGS_STATUS = Internal.createIndex(DSL.name("idx_borrowings_status"), Borrowings.BORROWINGS, new OrderField[]{Borrowings.BORROWINGS.STATUS}, false);
    public static final Index IDX_READERS_EMAIL = Internal.createIndex(DSL.name("idx_readers_email"), Readers.READERS, new OrderField[]{Readers.READERS.EMAIL}, false);
}
