/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.*;
import com.example.jooq.tables.records.*;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthorsRecord> AUTHORS_PKEY = Internal.createUniqueKey(Authors.AUTHORS, DSL.name("authors_pkey"), new TableField[]{Authors.AUTHORS.ID}, true);
    public static final UniqueKey<BooksRecord> BOOKS_PKEY = Internal.createUniqueKey(Books.BOOKS, DSL.name("books_pkey"), new TableField[]{Books.BOOKS.ID}, true);
    public static final UniqueKey<BorrowingsRecord> BORROWINGS_PKEY = Internal.createUniqueKey(Borrowings.BORROWINGS, DSL.name("borrowings_pkey"), new TableField[]{Borrowings.BORROWINGS.ID}, true);
    public static final UniqueKey<DatabasechangeloglockRecord> DATABASECHANGELOGLOCK_PKEY = Internal.createUniqueKey(Databasechangeloglock.DATABASECHANGELOGLOCK, DSL.name("databasechangeloglock_pkey"), new TableField[]{Databasechangeloglock.DATABASECHANGELOGLOCK.ID}, true);
    public static final UniqueKey<GenresRecord> GENRES_NAME_KEY = Internal.createUniqueKey(Genres.GENRES, DSL.name("genres_name_key"), new TableField[]{Genres.GENRES.NAME}, true);
    public static final UniqueKey<GenresRecord> GENRES_PKEY = Internal.createUniqueKey(Genres.GENRES, DSL.name("genres_pkey"), new TableField[]{Genres.GENRES.ID}, true);
    public static final UniqueKey<ReadersRecord> READERS_EMAIL_KEY = Internal.createUniqueKey(Readers.READERS, DSL.name("readers_email_key"), new TableField[]{Readers.READERS.EMAIL}, true);
    public static final UniqueKey<ReadersRecord> READERS_PKEY = Internal.createUniqueKey(Readers.READERS, DSL.name("readers_pkey"), new TableField[]{Readers.READERS.ID}, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BooksRecord, AuthorsRecord> BOOKS__BOOKS_AUTHOR_ID_FKEY = Internal.createForeignKey(Books.BOOKS, DSL.name("books_author_id_fkey"), new TableField[]{Books.BOOKS.AUTHOR_ID}, Keys.AUTHORS_PKEY, new TableField[]{Authors.AUTHORS.ID}, true);
    public static final ForeignKey<BooksRecord, GenresRecord> BOOKS__BOOKS_GENRE_ID_FKEY = Internal.createForeignKey(Books.BOOKS, DSL.name("books_genre_id_fkey"), new TableField[]{Books.BOOKS.GENRE_ID}, Keys.GENRES_PKEY, new TableField[]{Genres.GENRES.ID}, true);
    public static final ForeignKey<BorrowingsRecord, BooksRecord> BORROWINGS__BORROWINGS_BOOK_ID_FKEY = Internal.createForeignKey(Borrowings.BORROWINGS, DSL.name("borrowings_book_id_fkey"), new TableField[]{Borrowings.BORROWINGS.BOOK_ID}, Keys.BOOKS_PKEY, new TableField[]{Books.BOOKS.ID}, true);
    public static final ForeignKey<BorrowingsRecord, ReadersRecord> BORROWINGS__BORROWINGS_READER_ID_FKEY = Internal.createForeignKey(Borrowings.BORROWINGS, DSL.name("borrowings_reader_id_fkey"), new TableField[]{Borrowings.BORROWINGS.READER_ID}, Keys.READERS_PKEY, new TableField[]{Readers.READERS.ID}, true);
}
