/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.active_borrowings</code>.
     */
    public final ActiveBorrowings ACTIVE_BORROWINGS = ActiveBorrowings.ACTIVE_BORROWINGS;

    /**
     * The table <code>public.authors</code>.
     */
    public final Authors AUTHORS = Authors.AUTHORS;

    /**
     * The table <code>public.books</code>.
     */
    public final Books BOOKS = Books.BOOKS;

    /**
     * The table <code>public.borrowings</code>.
     */
    public final Borrowings BORROWINGS = Borrowings.BORROWINGS;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.genres</code>.
     */
    public final Genres GENRES = Genres.GENRES;

    /**
     * The table <code>public.readers</code>.
     */
    public final Readers READERS = Readers.READERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
                ActiveBorrowings.ACTIVE_BORROWINGS,
                Authors.AUTHORS,
                Books.BOOKS,
                Borrowings.BORROWINGS,
                Databasechangelog.DATABASECHANGELOG,
                Databasechangeloglock.DATABASECHANGELOGLOCK,
                Genres.GENRES,
                Readers.READERS
        );
    }
}
