/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.*;
import com.example.jooq.tables.Databasechangelog;
import com.example.jooq.tables.Databasechangeloglock;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>public.active_borrowings</code>.
     */
    public static final ActiveBorrowings ACTIVE_BORROWINGS = ActiveBorrowings.ACTIVE_BORROWINGS;

    /**
     * The table <code>public.authors</code>.
     */
    public static final Authors AUTHORS = Authors.AUTHORS;

    /**
     * The table <code>public.books</code>.
     */
    public static final Books BOOKS = Books.BOOKS;

    /**
     * The table <code>public.borrowings</code>.
     */
    public static final Borrowings BORROWINGS = Borrowings.BORROWINGS;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.genres</code>.
     */
    public static final Genres GENRES = Genres.GENRES;

    /**
     * The table <code>public.readers</code>.
     */
    public static final Readers READERS = Readers.READERS;
}
