/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;
import com.example.jooq.Public;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public enum BorrowingStatus implements EnumType {

    BORROWED("BORROWED"),

    RETURNED("RETURNED"),

    OVERDUE("OVERDUE");

    private final String literal;

    private BorrowingStatus(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "borrowing_status";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static BorrowingStatus lookupLiteral(String literal) {
        return EnumType.lookupLiteral(BorrowingStatus.class, literal);
    }
}
