/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.pojos.ActiveBorrowings;
import org.jooq.impl.TableRecordImpl;

import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ActiveBorrowingsRecord extends TableRecordImpl<ActiveBorrowingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.active_borrowings.borrowing_id</code>.
     */
    public void setBorrowingId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.active_borrowings.borrowing_id</code>.
     */
    public Long getBorrowingId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.active_borrowings.reader_name</code>.
     */
    public void setReaderName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.active_borrowings.reader_name</code>.
     */
    public String getReaderName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.active_borrowings.book_title</code>.
     */
    public void setBookTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.active_borrowings.book_title</code>.
     */
    public String getBookTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.active_borrowings.borrowed_date</code>.
     */
    public void setBorrowedDate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.active_borrowings.borrowed_date</code>.
     */
    public LocalDate getBorrowedDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>public.active_borrowings.days_borrowed</code>.
     */
    public void setDaysBorrowed(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.active_borrowings.days_borrowed</code>.
     */
    public Integer getDaysBorrowed() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActiveBorrowingsRecord
     */
    public ActiveBorrowingsRecord() {
        super(com.example.jooq.tables.ActiveBorrowings.ACTIVE_BORROWINGS);
    }

    /**
     * Create a detached, initialised ActiveBorrowingsRecord
     */
    public ActiveBorrowingsRecord(Long borrowingId, String readerName, String bookTitle, LocalDate borrowedDate, Integer daysBorrowed) {
        super(com.example.jooq.tables.ActiveBorrowings.ACTIVE_BORROWINGS);

        setBorrowingId(borrowingId);
        setReaderName(readerName);
        setBookTitle(bookTitle);
        setBorrowedDate(borrowedDate);
        setDaysBorrowed(daysBorrowed);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ActiveBorrowingsRecord
     */
    public ActiveBorrowingsRecord(ActiveBorrowings value) {
        super(com.example.jooq.tables.ActiveBorrowings.ACTIVE_BORROWINGS);

        if (value != null) {
            setBorrowingId(value.getBorrowingId());
            setReaderName(value.getReaderName());
            setBookTitle(value.getBookTitle());
            setBorrowedDate(value.getBorrowedDate());
            setDaysBorrowed(value.getDaysBorrowed());
            resetChangedOnNotNull();
        }
    }
}
