/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.pojos.Authors;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AuthorsRecord extends UpdatableRecordImpl<AuthorsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.authors.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.authors.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.authors.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.authors.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.authors.birth_date</code>.
     */
    public void setBirthDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.authors.birth_date</code>.
     */
    public LocalDate getBirthDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>public.authors.country</code>.
     */
    public void setCountry(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.authors.country</code>.
     */
    public String getCountry() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthorsRecord
     */
    public AuthorsRecord() {
        super(com.example.jooq.tables.Authors.AUTHORS);
    }

    /**
     * Create a detached, initialised AuthorsRecord
     */
    public AuthorsRecord(Long id, String name, LocalDate birthDate, String country) {
        super(com.example.jooq.tables.Authors.AUTHORS);

        setId(id);
        setName(name);
        setBirthDate(birthDate);
        setCountry(country);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AuthorsRecord
     */
    public AuthorsRecord(Authors value) {
        super(com.example.jooq.tables.Authors.AUTHORS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setBirthDate(value.getBirthDate());
            setCountry(value.getCountry());
            resetChangedOnNotNull();
        }
    }
}
