/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.pojos.Books;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class BooksRecord extends UpdatableRecordImpl<BooksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.books.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.books.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.books.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.books.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.books.author_id</code>.
     */
    public void setAuthorId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.books.author_id</code>.
     */
    public Long getAuthorId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.books.genre_id</code>.
     */
    public void setGenreId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.books.genre_id</code>.
     */
    public Long getGenreId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.books.published_year</code>.
     */
    public void setPublishedYear(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.books.published_year</code>.
     */
    public Integer getPublishedYear() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.books.available_copies</code>.
     */
    public void setAvailableCopies(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.books.available_copies</code>.
     */
    public Integer getAvailableCopies() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.books.total_copies</code>.
     */
    public void setTotalCopies(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.books.total_copies</code>.
     */
    public Integer getTotalCopies() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BooksRecord
     */
    public BooksRecord() {
        super(com.example.jooq.tables.Books.BOOKS);
    }

    /**
     * Create a detached, initialised BooksRecord
     */
    public BooksRecord(Long id, String title, Long authorId, Long genreId, Integer publishedYear, Integer availableCopies, Integer totalCopies) {
        super(com.example.jooq.tables.Books.BOOKS);

        setId(id);
        setTitle(title);
        setAuthorId(authorId);
        setGenreId(genreId);
        setPublishedYear(publishedYear);
        setAvailableCopies(availableCopies);
        setTotalCopies(totalCopies);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised BooksRecord
     */
    public BooksRecord(Books value) {
        super(com.example.jooq.tables.Books.BOOKS);

        if (value != null) {
            setId(value.getId());
            setTitle(value.getTitle());
            setAuthorId(value.getAuthorId());
            setGenreId(value.getGenreId());
            setPublishedYear(value.getPublishedYear());
            setAvailableCopies(value.getAvailableCopies());
            setTotalCopies(value.getTotalCopies());
            resetChangedOnNotNull();
        }
    }
}
