/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.pojos.Borrowings;
import com.example.jooq.enums.BorrowingStatus;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class BorrowingsRecord extends UpdatableRecordImpl<BorrowingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.borrowings.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.borrowings.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.borrowings.book_id</code>.
     */
    public void setBookId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.borrowings.book_id</code>.
     */
    public Long getBookId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.borrowings.reader_id</code>.
     */
    public void setReaderId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.borrowings.reader_id</code>.
     */
    public Long getReaderId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.borrowings.borrowed_date</code>.
     */
    public void setBorrowedDate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.borrowings.borrowed_date</code>.
     */
    public LocalDate getBorrowedDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>public.borrowings.due_date</code>.
     */
    public void setDueDate(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.borrowings.due_date</code>.
     */
    public LocalDate getDueDate() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>public.borrowings.returned_date</code>.
     */
    public void setReturnedDate(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.borrowings.returned_date</code>.
     */
    public LocalDate getReturnedDate() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>public.borrowings.status</code>.
     */
    public void setStatus(BorrowingStatus value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.borrowings.status</code>.
     */
    public BorrowingStatus getStatus() {
        return (BorrowingStatus) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BorrowingsRecord
     */
    public BorrowingsRecord() {
        super(com.example.jooq.tables.Borrowings.BORROWINGS);
    }

    /**
     * Create a detached, initialised BorrowingsRecord
     */
    public BorrowingsRecord(Long id, Long bookId, Long readerId, LocalDate borrowedDate, LocalDate dueDate, LocalDate returnedDate, BorrowingStatus status) {
        super(com.example.jooq.tables.Borrowings.BORROWINGS);

        setId(id);
        setBookId(bookId);
        setReaderId(readerId);
        setBorrowedDate(borrowedDate);
        setDueDate(dueDate);
        setReturnedDate(returnedDate);
        setStatus(status);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised BorrowingsRecord
     */
    public BorrowingsRecord(Borrowings value) {
        super(com.example.jooq.tables.Borrowings.BORROWINGS);

        if (value != null) {
            setId(value.getId());
            setBookId(value.getBookId());
            setReaderId(value.getReaderId());
            setBorrowedDate(value.getBorrowedDate());
            setDueDate(value.getDueDate());
            setReturnedDate(value.getReturnedDate());
            resetChangedOnNotNull();
        }
    }
}
