/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.pojos.Genres;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class GenresRecord extends UpdatableRecordImpl<GenresRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.genres.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.genres.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.genres.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.genres.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GenresRecord
     */
    public GenresRecord() {
        super(com.example.jooq.tables.Genres.GENRES);
    }

    /**
     * Create a detached, initialised GenresRecord
     */
    public GenresRecord(Long id, String name) {
        super(com.example.jooq.tables.Genres.GENRES);

        setId(id);
        setName(name);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised GenresRecord
     */
    public GenresRecord(Genres value) {
        super(com.example.jooq.tables.Genres.GENRES);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            resetChangedOnNotNull();
        }
    }
}
