/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.records;


import com.example.jooq.tables.pojos.Readers;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ReadersRecord extends UpdatableRecordImpl<ReadersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.readers.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.readers.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.readers.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.readers.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.readers.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.readers.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.readers.phone</code>.
     */
    public void setPhone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.readers.phone</code>.
     */
    public String getPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.readers.membership_date</code>.
     */
    public void setMembershipDate(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.readers.membership_date</code>.
     */
    public LocalDate getMembershipDate() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>public.readers.is_active</code>.
     */
    public void setIsActive(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.readers.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReadersRecord
     */
    public ReadersRecord() {
        super(com.example.jooq.tables.Readers.READERS);
    }

    /**
     * Create a detached, initialised ReadersRecord
     */
    public ReadersRecord(Long id, String name, String email, String phone, LocalDate membershipDate, Boolean isActive) {
        super(com.example.jooq.tables.Readers.READERS);

        setId(id);
        setName(name);
        setEmail(email);
        setPhone(phone);
        setMembershipDate(membershipDate);
        setIsActive(isActive);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ReadersRecord
     */
    public ReadersRecord(Readers value) {
        super(com.example.jooq.tables.Readers.READERS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setEmail(value.getEmail());
            setPhone(value.getPhone());
            setMembershipDate(value.getMembershipDate());
            setIsActive(value.getIsActive());
            resetChangedOnNotNull();
        }
    }
}
