/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ActiveBorrowings implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long borrowingId;
    private String readerName;
    private String bookTitle;
    private LocalDate borrowedDate;
    private Integer daysBorrowed;

    public ActiveBorrowings() {
    }

    public ActiveBorrowings(ActiveBorrowings value) {
        this.borrowingId = value.borrowingId;
        this.readerName = value.readerName;
        this.bookTitle = value.bookTitle;
        this.borrowedDate = value.borrowedDate;
        this.daysBorrowed = value.daysBorrowed;
    }

    public ActiveBorrowings(
            Long borrowingId,
            String readerName,
            String bookTitle,
            LocalDate borrowedDate,
            Integer daysBorrowed
    ) {
        this.borrowingId = borrowingId;
        this.readerName = readerName;
        this.bookTitle = bookTitle;
        this.borrowedDate = borrowedDate;
        this.daysBorrowed = daysBorrowed;
    }

    /**
     * Getter for <code>public.active_borrowings.borrowing_id</code>.
     */
    public Long getBorrowingId() {
        return this.borrowingId;
    }

    /**
     * Setter for <code>public.active_borrowings.borrowing_id</code>.
     */
    public void setBorrowingId(Long borrowingId) {
        this.borrowingId = borrowingId;
    }

    /**
     * Getter for <code>public.active_borrowings.reader_name</code>.
     */
    public String getReaderName() {
        return this.readerName;
    }

    /**
     * Setter for <code>public.active_borrowings.reader_name</code>.
     */
    public void setReaderName(String readerName) {
        this.readerName = readerName;
    }

    /**
     * Getter for <code>public.active_borrowings.book_title</code>.
     */
    public String getBookTitle() {
        return this.bookTitle;
    }

    /**
     * Setter for <code>public.active_borrowings.book_title</code>.
     */
    public void setBookTitle(String bookTitle) {
        this.bookTitle = bookTitle;
    }

    /**
     * Getter for <code>public.active_borrowings.borrowed_date</code>.
     */
    public LocalDate getBorrowedDate() {
        return this.borrowedDate;
    }

    /**
     * Setter for <code>public.active_borrowings.borrowed_date</code>.
     */
    public void setBorrowedDate(LocalDate borrowedDate) {
        this.borrowedDate = borrowedDate;
    }

    /**
     * Getter for <code>public.active_borrowings.days_borrowed</code>.
     */
    public Integer getDaysBorrowed() {
        return this.daysBorrowed;
    }

    /**
     * Setter for <code>public.active_borrowings.days_borrowed</code>.
     */
    public void setDaysBorrowed(Integer daysBorrowed) {
        this.daysBorrowed = daysBorrowed;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ActiveBorrowings other = (ActiveBorrowings) obj;
        if (this.borrowingId == null) {
            if (other.borrowingId != null)
                return false;
        } else if (!this.borrowingId.equals(other.borrowingId))
            return false;
        if (this.readerName == null) {
            if (other.readerName != null)
                return false;
        } else if (!this.readerName.equals(other.readerName))
            return false;
        if (this.bookTitle == null) {
            if (other.bookTitle != null)
                return false;
        } else if (!this.bookTitle.equals(other.bookTitle))
            return false;
        if (this.borrowedDate == null) {
            if (other.borrowedDate != null)
                return false;
        } else if (!this.borrowedDate.equals(other.borrowedDate))
            return false;
        if (this.daysBorrowed == null) {
            if (other.daysBorrowed != null)
                return false;
        } else if (!this.daysBorrowed.equals(other.daysBorrowed))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.borrowingId == null) ? 0 : this.borrowingId.hashCode());
        result = prime * result + ((this.readerName == null) ? 0 : this.readerName.hashCode());
        result = prime * result + ((this.bookTitle == null) ? 0 : this.bookTitle.hashCode());
        result = prime * result + ((this.borrowedDate == null) ? 0 : this.borrowedDate.hashCode());
        result = prime * result + ((this.daysBorrowed == null) ? 0 : this.daysBorrowed.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ActiveBorrowings (");

        sb.append(borrowingId);
        sb.append(", ").append(readerName);
        sb.append(", ").append(bookTitle);
        sb.append(", ").append(borrowedDate);
        sb.append(", ").append(daysBorrowed);

        sb.append(")");
        return sb.toString();
    }
}
