/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Books implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String title;
    private Long authorId;
    private Long genreId;
    private Integer publishedYear;
    private Integer availableCopies;
    private Integer totalCopies;

    public Books() {
    }

    public Books(Books value) {
        this.id = value.id;
        this.title = value.title;
        this.authorId = value.authorId;
        this.genreId = value.genreId;
        this.publishedYear = value.publishedYear;
        this.availableCopies = value.availableCopies;
        this.totalCopies = value.totalCopies;
    }

    public Books(
            Long id,
            String title,
            Long authorId,
            Long genreId,
            Integer publishedYear,
            Integer availableCopies,
            Integer totalCopies
    ) {
        this.id = id;
        this.title = title;
        this.authorId = authorId;
        this.genreId = genreId;
        this.publishedYear = publishedYear;
        this.availableCopies = availableCopies;
        this.totalCopies = totalCopies;
    }

    /**
     * Getter for <code>public.books.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.books.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.books.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>public.books.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>public.books.author_id</code>.
     */
    public Long getAuthorId() {
        return this.authorId;
    }

    /**
     * Setter for <code>public.books.author_id</code>.
     */
    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }

    /**
     * Getter for <code>public.books.genre_id</code>.
     */
    public Long getGenreId() {
        return this.genreId;
    }

    /**
     * Setter for <code>public.books.genre_id</code>.
     */
    public void setGenreId(Long genreId) {
        this.genreId = genreId;
    }

    /**
     * Getter for <code>public.books.published_year</code>.
     */
    public Integer getPublishedYear() {
        return this.publishedYear;
    }

    /**
     * Setter for <code>public.books.published_year</code>.
     */
    public void setPublishedYear(Integer publishedYear) {
        this.publishedYear = publishedYear;
    }

    /**
     * Getter for <code>public.books.available_copies</code>.
     */
    public Integer getAvailableCopies() {
        return this.availableCopies;
    }

    /**
     * Setter for <code>public.books.available_copies</code>.
     */
    public void setAvailableCopies(Integer availableCopies) {
        this.availableCopies = availableCopies;
    }

    /**
     * Getter for <code>public.books.total_copies</code>.
     */
    public Integer getTotalCopies() {
        return this.totalCopies;
    }

    /**
     * Setter for <code>public.books.total_copies</code>.
     */
    public void setTotalCopies(Integer totalCopies) {
        this.totalCopies = totalCopies;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Books other = (Books) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        } else if (!this.id.equals(other.id))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        } else if (!this.title.equals(other.title))
            return false;
        if (this.authorId == null) {
            if (other.authorId != null)
                return false;
        } else if (!this.authorId.equals(other.authorId))
            return false;
        if (this.genreId == null) {
            if (other.genreId != null)
                return false;
        } else if (!this.genreId.equals(other.genreId))
            return false;
        if (this.publishedYear == null) {
            if (other.publishedYear != null)
                return false;
        } else if (!this.publishedYear.equals(other.publishedYear))
            return false;
        if (this.availableCopies == null) {
            if (other.availableCopies != null)
                return false;
        } else if (!this.availableCopies.equals(other.availableCopies))
            return false;
        if (this.totalCopies == null) {
            if (other.totalCopies != null)
                return false;
        } else if (!this.totalCopies.equals(other.totalCopies))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.authorId == null) ? 0 : this.authorId.hashCode());
        result = prime * result + ((this.genreId == null) ? 0 : this.genreId.hashCode());
        result = prime * result + ((this.publishedYear == null) ? 0 : this.publishedYear.hashCode());
        result = prime * result + ((this.availableCopies == null) ? 0 : this.availableCopies.hashCode());
        result = prime * result + ((this.totalCopies == null) ? 0 : this.totalCopies.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Books (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(authorId);
        sb.append(", ").append(genreId);
        sb.append(", ").append(publishedYear);
        sb.append(", ").append(availableCopies);
        sb.append(", ").append(totalCopies);

        sb.append(")");
        return sb.toString();
    }
}
