/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.pojos;


import com.example.jooq.enums.BorrowingStatus;

import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Borrowings implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long bookId;
    private Long readerId;
    private LocalDate borrowedDate;
    private LocalDate dueDate;
    private LocalDate returnedDate;
    private BorrowingStatus status;

    public Borrowings() {
    }

    public Borrowings(Borrowings value) {
        this.id = value.id;
        this.bookId = value.bookId;
        this.readerId = value.readerId;
        this.borrowedDate = value.borrowedDate;
        this.dueDate = value.dueDate;
        this.returnedDate = value.returnedDate;
        this.status = value.status;
    }

    public Borrowings(
            Long id,
            Long bookId,
            Long readerId,
            LocalDate borrowedDate,
            LocalDate dueDate,
            LocalDate returnedDate,
            BorrowingStatus status
    ) {
        this.id = id;
        this.bookId = bookId;
        this.readerId = readerId;
        this.borrowedDate = borrowedDate;
        this.dueDate = dueDate;
        this.returnedDate = returnedDate;
        this.status = status;
    }

    /**
     * Getter for <code>public.borrowings.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.borrowings.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.borrowings.book_id</code>.
     */
    public Long getBookId() {
        return this.bookId;
    }

    /**
     * Setter for <code>public.borrowings.book_id</code>.
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * Getter for <code>public.borrowings.reader_id</code>.
     */
    public Long getReaderId() {
        return this.readerId;
    }

    /**
     * Setter for <code>public.borrowings.reader_id</code>.
     */
    public void setReaderId(Long readerId) {
        this.readerId = readerId;
    }

    /**
     * Getter for <code>public.borrowings.borrowed_date</code>.
     */
    public LocalDate getBorrowedDate() {
        return this.borrowedDate;
    }

    /**
     * Setter for <code>public.borrowings.borrowed_date</code>.
     */
    public void setBorrowedDate(LocalDate borrowedDate) {
        this.borrowedDate = borrowedDate;
    }

    /**
     * Getter for <code>public.borrowings.due_date</code>.
     */
    public LocalDate getDueDate() {
        return this.dueDate;
    }

    /**
     * Setter for <code>public.borrowings.due_date</code>.
     */
    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * Getter for <code>public.borrowings.returned_date</code>.
     */
    public LocalDate getReturnedDate() {
        return this.returnedDate;
    }

    /**
     * Setter for <code>public.borrowings.returned_date</code>.
     */
    public void setReturnedDate(LocalDate returnedDate) {
        this.returnedDate = returnedDate;
    }

    /**
     * Getter for <code>public.borrowings.status</code>.
     */
    public BorrowingStatus getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.borrowings.status</code>.
     */
    public void setStatus(BorrowingStatus status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Borrowings other = (Borrowings) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        } else if (!this.id.equals(other.id))
            return false;
        if (this.bookId == null) {
            if (other.bookId != null)
                return false;
        } else if (!this.bookId.equals(other.bookId))
            return false;
        if (this.readerId == null) {
            if (other.readerId != null)
                return false;
        } else if (!this.readerId.equals(other.readerId))
            return false;
        if (this.borrowedDate == null) {
            if (other.borrowedDate != null)
                return false;
        } else if (!this.borrowedDate.equals(other.borrowedDate))
            return false;
        if (this.dueDate == null) {
            if (other.dueDate != null)
                return false;
        } else if (!this.dueDate.equals(other.dueDate))
            return false;
        if (this.returnedDate == null) {
            if (other.returnedDate != null)
                return false;
        } else if (!this.returnedDate.equals(other.returnedDate))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        } else if (!this.status.equals(other.status))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.bookId == null) ? 0 : this.bookId.hashCode());
        result = prime * result + ((this.readerId == null) ? 0 : this.readerId.hashCode());
        result = prime * result + ((this.borrowedDate == null) ? 0 : this.borrowedDate.hashCode());
        result = prime * result + ((this.dueDate == null) ? 0 : this.dueDate.hashCode());
        result = prime * result + ((this.returnedDate == null) ? 0 : this.returnedDate.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Borrowings (");

        sb.append(id);
        sb.append(", ").append(bookId);
        sb.append(", ").append(readerId);
        sb.append(", ").append(borrowedDate);
        sb.append(", ").append(dueDate);
        sb.append(", ").append(returnedDate);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
