/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Readers implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private String email;
    private String phone;
    private LocalDate membershipDate;
    private Boolean isActive;

    public Readers() {
    }

    public Readers(Readers value) {
        this.id = value.id;
        this.name = value.name;
        this.email = value.email;
        this.phone = value.phone;
        this.membershipDate = value.membershipDate;
        this.isActive = value.isActive;
    }

    public Readers(
            Long id,
            String name,
            String email,
            String phone,
            LocalDate membershipDate,
            Boolean isActive
    ) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.membershipDate = membershipDate;
        this.isActive = isActive;
    }

    /**
     * Getter for <code>public.readers.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.readers.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.readers.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.readers.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.readers.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.readers.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>public.readers.phone</code>.
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>public.readers.phone</code>.
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Getter for <code>public.readers.membership_date</code>.
     */
    public LocalDate getMembershipDate() {
        return this.membershipDate;
    }

    /**
     * Setter for <code>public.readers.membership_date</code>.
     */
    public void setMembershipDate(LocalDate membershipDate) {
        this.membershipDate = membershipDate;
    }

    /**
     * Getter for <code>public.readers.is_active</code>.
     */
    public Boolean getIsActive() {
        return this.isActive;
    }

    /**
     * Setter for <code>public.readers.is_active</code>.
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Readers other = (Readers) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        } else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        } else if (!this.name.equals(other.name))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        } else if (!this.email.equals(other.email))
            return false;
        if (this.phone == null) {
            if (other.phone != null)
                return false;
        } else if (!this.phone.equals(other.phone))
            return false;
        if (this.membershipDate == null) {
            if (other.membershipDate != null)
                return false;
        } else if (!this.membershipDate.equals(other.membershipDate))
            return false;
        if (this.isActive == null) {
            if (other.isActive != null)
                return false;
        } else if (!this.isActive.equals(other.isActive))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.phone == null) ? 0 : this.phone.hashCode());
        result = prime * result + ((this.membershipDate == null) ? 0 : this.membershipDate.hashCode());
        result = prime * result + ((this.isActive == null) ? 0 : this.isActive.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Readers (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(email);
        sb.append(", ").append(phone);
        sb.append(", ").append(membershipDate);
        sb.append(", ").append(isActive);

        sb.append(")");
        return sb.toString();
    }
}
