/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.Public;
import com.example.jooq.tables.records.ActiveBorrowingsRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.time.LocalDate;
import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ActiveBorrowings extends TableImpl<ActiveBorrowingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.active_borrowings</code>
     */
    public static final ActiveBorrowings ACTIVE_BORROWINGS = new ActiveBorrowings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActiveBorrowingsRecord> getRecordType() {
        return ActiveBorrowingsRecord.class;
    }

    /**
     * The column <code>public.active_borrowings.borrowing_id</code>.
     */
    public final TableField<ActiveBorrowingsRecord, Long> BORROWING_ID = createField(DSL.name("borrowing_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.active_borrowings.reader_name</code>.
     */
    public final TableField<ActiveBorrowingsRecord, String> READER_NAME = createField(DSL.name("reader_name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.active_borrowings.book_title</code>.
     */
    public final TableField<ActiveBorrowingsRecord, String> BOOK_TITLE = createField(DSL.name("book_title"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>public.active_borrowings.borrowed_date</code>.
     */
    public final TableField<ActiveBorrowingsRecord, LocalDate> BORROWED_DATE = createField(DSL.name("borrowed_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.active_borrowings.days_borrowed</code>.
     */
    public final TableField<ActiveBorrowingsRecord, Integer> DAYS_BORROWED = createField(DSL.name("days_borrowed"), SQLDataType.INTEGER, this, "");

    private ActiveBorrowings(Name alias, Table<ActiveBorrowingsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ActiveBorrowings(Name alias, Table<ActiveBorrowingsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
                create view "active_borrowings" as  SELECT b.id AS borrowing_id,
                  r.name AS reader_name,
                  bk.title AS book_title,
                  b.borrowed_date,
                  (CURRENT_DATE - b.borrowed_date) AS days_borrowed
                 FROM ((borrowings b
                   JOIN readers r ON ((b.reader_id = r.id)))
                   JOIN books bk ON ((b.book_id = bk.id)))
                WHERE (b.returned_date IS NULL);
                """), where);
    }

    /**
     * Create an aliased <code>public.active_borrowings</code> table reference
     */
    public ActiveBorrowings(String alias) {
        this(DSL.name(alias), ACTIVE_BORROWINGS);
    }

    /**
     * Create an aliased <code>public.active_borrowings</code> table reference
     */
    public ActiveBorrowings(Name alias) {
        this(alias, ACTIVE_BORROWINGS);
    }

    /**
     * Create a <code>public.active_borrowings</code> table reference
     */
    public ActiveBorrowings() {
        this(DSL.name("active_borrowings"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public ActiveBorrowings as(String alias) {
        return new ActiveBorrowings(DSL.name(alias), this);
    }

    @Override
    public ActiveBorrowings as(Name alias) {
        return new ActiveBorrowings(alias, this);
    }

    @Override
    public ActiveBorrowings as(Table<?> alias) {
        return new ActiveBorrowings(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActiveBorrowings rename(String name) {
        return new ActiveBorrowings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActiveBorrowings rename(Name name) {
        return new ActiveBorrowings(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActiveBorrowings rename(Table<?> name) {
        return new ActiveBorrowings(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActiveBorrowings where(Condition condition) {
        return new ActiveBorrowings(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActiveBorrowings where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActiveBorrowings where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActiveBorrowings where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ActiveBorrowings where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ActiveBorrowings where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ActiveBorrowings where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ActiveBorrowings where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActiveBorrowings whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ActiveBorrowings whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
