/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.tables.Books.BooksPath;
import com.example.jooq.tables.records.AuthorsRecord;
import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import com.example.jooq.Keys;
import com.example.jooq.Public;

import java.time.LocalDate;
import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Authors extends TableImpl<AuthorsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.authors</code>
     */
    public static final Authors AUTHORS = new Authors();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthorsRecord> getRecordType() {
        return AuthorsRecord.class;
    }

    /**
     * The column <code>public.authors.id</code>.
     */
    public final TableField<AuthorsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.authors.name</code>.
     */
    public final TableField<AuthorsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.authors.birth_date</code>.
     */
    public final TableField<AuthorsRecord, LocalDate> BIRTH_DATE = createField(DSL.name("birth_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.authors.country</code>.
     */
    public final TableField<AuthorsRecord, String> COUNTRY = createField(DSL.name("country"), SQLDataType.VARCHAR(50), this, "");

    private Authors(Name alias, Table<AuthorsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Authors(Name alias, Table<AuthorsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.authors</code> table reference
     */
    public Authors(String alias) {
        this(DSL.name(alias), AUTHORS);
    }

    /**
     * Create an aliased <code>public.authors</code> table reference
     */
    public Authors(Name alias) {
        this(alias, AUTHORS);
    }

    /**
     * Create a <code>public.authors</code> table reference
     */
    public Authors() {
        this(DSL.name("authors"), null);
    }

    public <O extends Record> Authors(Table<O> path, ForeignKey<O, AuthorsRecord> childPath, InverseForeignKey<O, AuthorsRecord> parentPath) {
        super(path, childPath, parentPath, AUTHORS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AuthorsPath extends Authors implements Path<AuthorsRecord> {

        private static final long serialVersionUID = 1L;

        public <O extends Record> AuthorsPath(Table<O> path, ForeignKey<O, AuthorsRecord> childPath, InverseForeignKey<O, AuthorsRecord> parentPath) {
            super(path, childPath, parentPath);
        }

        private AuthorsPath(Name alias, Table<AuthorsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AuthorsPath as(String alias) {
            return new AuthorsPath(DSL.name(alias), this);
        }

        @Override
        public AuthorsPath as(Name alias) {
            return new AuthorsPath(alias, this);
        }

        @Override
        public AuthorsPath as(Table<?> alias) {
            return new AuthorsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<AuthorsRecord, Long> getIdentity() {
        return (Identity<AuthorsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AuthorsRecord> getPrimaryKey() {
        return Keys.AUTHORS_PKEY;
    }

    private transient BooksPath _books;

    /**
     * Get the implicit to-many join path to the <code>public.books</code> table
     */
    public BooksPath books() {
        if (_books == null)
            _books = new BooksPath(this, null, Keys.BOOKS__BOOKS_AUTHOR_ID_FKEY.getInverseKey());

        return _books;
    }

    @Override
    public Authors as(String alias) {
        return new Authors(DSL.name(alias), this);
    }

    @Override
    public Authors as(Name alias) {
        return new Authors(alias, this);
    }

    @Override
    public Authors as(Table<?> alias) {
        return new Authors(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Authors rename(String name) {
        return new Authors(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Authors rename(Name name) {
        return new Authors(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Authors rename(Table<?> name) {
        return new Authors(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Authors where(Condition condition) {
        return new Authors(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Authors where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Authors where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Authors where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Authors where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Authors where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Authors where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Authors where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Authors whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Authors whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
