/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.tables.records.BooksRecord;
import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import com.example.jooq.Indexes;
import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.Authors.AuthorsPath;
import com.example.jooq.tables.Borrowings.BorrowingsPath;
import com.example.jooq.tables.Genres.GenresPath;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Books extends TableImpl<BooksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.books</code>
     */
    public static final Books BOOKS = new Books();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BooksRecord> getRecordType() {
        return BooksRecord.class;
    }

    /**
     * The column <code>public.books.id</code>.
     */
    public final TableField<BooksRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.books.title</code>.
     */
    public final TableField<BooksRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(500).nullable(false), this, "");

    /**
     * The column <code>public.books.author_id</code>.
     */
    public final TableField<BooksRecord, Long> AUTHOR_ID = createField(DSL.name("author_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.books.genre_id</code>.
     */
    public final TableField<BooksRecord, Long> GENRE_ID = createField(DSL.name("genre_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.books.published_year</code>.
     */
    public final TableField<BooksRecord, Integer> PUBLISHED_YEAR = createField(DSL.name("published_year"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.books.available_copies</code>.
     */
    public final TableField<BooksRecord, Integer> AVAILABLE_COPIES = createField(DSL.name("available_copies"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.books.total_copies</code>.
     */
    public final TableField<BooksRecord, Integer> TOTAL_COPIES = createField(DSL.name("total_copies"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    private Books(Name alias, Table<BooksRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Books(Name alias, Table<BooksRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.books</code> table reference
     */
    public Books(String alias) {
        this(DSL.name(alias), BOOKS);
    }

    /**
     * Create an aliased <code>public.books</code> table reference
     */
    public Books(Name alias) {
        this(alias, BOOKS);
    }

    /**
     * Create a <code>public.books</code> table reference
     */
    public Books() {
        this(DSL.name("books"), null);
    }

    public <O extends Record> Books(Table<O> path, ForeignKey<O, BooksRecord> childPath, InverseForeignKey<O, BooksRecord> parentPath) {
        super(path, childPath, parentPath, BOOKS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BooksPath extends Books implements Path<BooksRecord> {

        private static final long serialVersionUID = 1L;

        public <O extends Record> BooksPath(Table<O> path, ForeignKey<O, BooksRecord> childPath, InverseForeignKey<O, BooksRecord> parentPath) {
            super(path, childPath, parentPath);
        }

        private BooksPath(Name alias, Table<BooksRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BooksPath as(String alias) {
            return new BooksPath(DSL.name(alias), this);
        }

        @Override
        public BooksPath as(Name alias) {
            return new BooksPath(alias, this);
        }

        @Override
        public BooksPath as(Table<?> alias) {
            return new BooksPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_BOOKS_AUTHOR, Indexes.IDX_BOOKS_GENRE);
    }

    @Override
    public Identity<BooksRecord, Long> getIdentity() {
        return (Identity<BooksRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<BooksRecord> getPrimaryKey() {
        return Keys.BOOKS_PKEY;
    }

    @Override
    public List<ForeignKey<BooksRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BOOKS__BOOKS_AUTHOR_ID_FKEY, Keys.BOOKS__BOOKS_GENRE_ID_FKEY);
    }

    private transient AuthorsPath _authors;

    /**
     * Get the implicit join path to the <code>public.authors</code> table.
     */
    public AuthorsPath authors() {
        if (_authors == null)
            _authors = new AuthorsPath(this, Keys.BOOKS__BOOKS_AUTHOR_ID_FKEY, null);

        return _authors;
    }

    private transient GenresPath _genres;

    /**
     * Get the implicit join path to the <code>public.genres</code> table.
     */
    public GenresPath genres() {
        if (_genres == null)
            _genres = new GenresPath(this, Keys.BOOKS__BOOKS_GENRE_ID_FKEY, (Object) null);

        return _genres;
    }

    private transient BorrowingsPath _borrowings;

    /**
     * Get the implicit to-many join path to the <code>public.borrowings</code>
     * table
     */
    public BorrowingsPath borrowings() {
        if (_borrowings == null)
            _borrowings = new BorrowingsPath(this, null, Keys.BORROWINGS__BORROWINGS_BOOK_ID_FKEY.getInverseKey());

        return _borrowings;
    }

    @Override
    public List<Check<BooksRecord>> getChecks() {
        return Arrays.asList(
                Internal.createCheck(this, DSL.name("books_available_copies_check"), "((available_copies >= 0))", true),
                Internal.createCheck(this, DSL.name("books_published_year_check"), "((published_year > 0))", true),
                Internal.createCheck(this, DSL.name("books_total_copies_check"), "((total_copies >= 1))", true)
        );
    }

    @Override
    public Books as(String alias) {
        return new Books(DSL.name(alias), this);
    }

    @Override
    public Books as(Name alias) {
        return new Books(alias, this);
    }

    @Override
    public Books as(Table<?> alias) {
        return new Books(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Books rename(String name) {
        return new Books(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Books rename(Name name) {
        return new Books(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Books rename(Table<?> name) {
        return new Books(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Books where(Condition condition) {
        return new Books(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Books where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Books where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Books where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Books where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Books where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Books where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Books where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Books whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Books whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
