/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import com.example.jooq.enums.BorrowingStatus;
import com.example.jooq.tables.Books.BooksPath;
import com.example.jooq.tables.Readers.ReadersPath;
import com.example.jooq.tables.records.BorrowingsRecord;
import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import com.example.jooq.Indexes;
import com.example.jooq.Keys;
import com.example.jooq.Public;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Borrowings extends TableImpl<BorrowingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.borrowings</code>
     */
    public static final Borrowings BORROWINGS = new Borrowings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BorrowingsRecord> getRecordType() {
        return BorrowingsRecord.class;
    }

    /**
     * The column <code>public.borrowings.id</code>.
     */
    public final TableField<BorrowingsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.borrowings.book_id</code>.
     */
    public final TableField<BorrowingsRecord, Long> BOOK_ID = createField(DSL.name("book_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.borrowings.reader_id</code>.
     */
    public final TableField<BorrowingsRecord, Long> READER_ID = createField(DSL.name("reader_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.borrowings.borrowed_date</code>.
     */
    public final TableField<BorrowingsRecord, LocalDate> BORROWED_DATE = createField(DSL.name("borrowed_date"), SQLDataType.LOCALDATE.nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_DATE"), SQLDataType.LOCALDATE)), this, "");

    /**
     * The column <code>public.borrowings.due_date</code>.
     */
    public final TableField<BorrowingsRecord, LocalDate> DUE_DATE = createField(DSL.name("due_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>public.borrowings.returned_date</code>.
     */
    public final TableField<BorrowingsRecord, LocalDate> RETURNED_DATE = createField(DSL.name("returned_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.borrowings.status</code>.
     */
    public final TableField<BorrowingsRecord, BorrowingStatus> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field(DSL.raw("'BORROWED'::borrowing_status"), SQLDataType.VARCHAR)).asEnumDataType(BorrowingStatus.class), this, "");

    private Borrowings(Name alias, Table<BorrowingsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Borrowings(Name alias, Table<BorrowingsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.borrowings</code> table reference
     */
    public Borrowings(String alias) {
        this(DSL.name(alias), BORROWINGS);
    }

    /**
     * Create an aliased <code>public.borrowings</code> table reference
     */
    public Borrowings(Name alias) {
        this(alias, BORROWINGS);
    }

    /**
     * Create a <code>public.borrowings</code> table reference
     */
    public Borrowings() {
        this(DSL.name("borrowings"), null);
    }

    public <O extends Record> Borrowings(Table<O> path, ForeignKey<O, BorrowingsRecord> childPath, InverseForeignKey<O, BorrowingsRecord> parentPath) {
        super(path, childPath, parentPath, BORROWINGS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BorrowingsPath extends Borrowings implements Path<BorrowingsRecord> {

        private static final long serialVersionUID = 1L;

        public <O extends Record> BorrowingsPath(Table<O> path, ForeignKey<O, BorrowingsRecord> childPath, InverseForeignKey<O, BorrowingsRecord> parentPath) {
            super(path, childPath, parentPath);
        }

        private BorrowingsPath(Name alias, Table<BorrowingsRecord> aliased) {
            super(alias, aliased);
        }

//        public BorrowingsPath(Books books, Object childPath, @org.jetbrains.annotations.NotNull InverseForeignKey<BooksRecord,com.example.jooq.tables.records.BorrowingsRecord> inverseKey) {
//        }

        @Override
        public BorrowingsPath as(String alias) {
            return new BorrowingsPath(DSL.name(alias), this);
        }

        @Override
        public BorrowingsPath as(Name alias) {
            return new BorrowingsPath(alias, this);
        }

        @Override
        public BorrowingsPath as(Table<?> alias) {
            return new BorrowingsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_BORROWINGS_STATUS);
    }

    @Override
    public Identity<BorrowingsRecord, Long> getIdentity() {
        return (Identity<BorrowingsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<BorrowingsRecord> getPrimaryKey() {
        return Keys.BORROWINGS_PKEY;
    }

    @Override
    public List<ForeignKey<BorrowingsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BORROWINGS__BORROWINGS_BOOK_ID_FKEY, Keys.BORROWINGS__BORROWINGS_READER_ID_FKEY);
    }

    private transient BooksPath _books;

    /**
     * Get the implicit join path to the <code>public.books</code> table.
     */
    public BooksPath books() {
        if (_books == null)
            _books = new BooksPath(this, Keys.BORROWINGS__BORROWINGS_BOOK_ID_FKEY, null);

        return _books;
    }

    private transient ReadersPath _readers;

    /**
     * Get the implicit join path to the <code>public.readers</code> table.
     */
    public ReadersPath readers() {
        if (_readers == null)
            _readers = new ReadersPath(this, Keys.BORROWINGS__BORROWINGS_READER_ID_FKEY, (Object) null);

        return _readers;
    }

    @Override
    public Borrowings as(String alias) {
        return new Borrowings(DSL.name(alias), this);
    }

    @Override
    public Borrowings as(Name alias) {
        return new Borrowings(alias, this);
    }

    @Override
    public Borrowings as(Table<?> alias) {
        return new Borrowings(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Borrowings rename(String name) {
        return new Borrowings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Borrowings rename(Name name) {
        return new Borrowings(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Borrowings rename(Table<?> name) {
        return new Borrowings(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Borrowings where(Condition condition) {
        return new Borrowings(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Borrowings where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Borrowings where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Borrowings where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Borrowings where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Borrowings where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Borrowings where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Borrowings where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Borrowings whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Borrowings whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
