/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.Books.BooksPath;
import com.example.jooq.tables.records.BooksRecord;
import com.example.jooq.tables.records.GenresRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Genres extends TableImpl<GenresRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.genres</code>
     */
    public static final Genres GENRES = new Genres();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GenresRecord> getRecordType() {
        return GenresRecord.class;
    }

    /**
     * The column <code>public.genres.id</code>.
     */
    public final TableField<GenresRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.genres.name</code>.
     */
    public final TableField<GenresRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private Genres(Name alias, Table<GenresRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Genres(Name alias, Table<GenresRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.genres</code> table reference
     */
    public Genres(String alias) {
        this(DSL.name(alias), GENRES);
    }

    /**
     * Create an aliased <code>public.genres</code> table reference
     */
    public Genres(Name alias) {
        this(alias, GENRES);
    }

    /**
     * Create a <code>public.genres</code> table reference
     */
    public Genres() {
        this(DSL.name("genres"), null);
    }

    public <O extends Record> Genres(Table<O> path, ForeignKey<O, GenresRecord> childPath, InverseForeignKey<O, GenresRecord> parentPath) {
        super(path, childPath, parentPath, GENRES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GenresPath extends Genres implements Path<GenresRecord> {

        private static final long serialVersionUID = 1L;

        public <O extends Record> GenresPath(Table<O> path, ForeignKey<O, GenresRecord> childPath, InverseForeignKey<O, GenresRecord> parentPath) {
            super(path, childPath, parentPath);
        }

        private GenresPath(Name alias, Table<GenresRecord> aliased) {
            super(alias, aliased);
        }

        public GenresPath(Books books, ForeignKey<BooksRecord, GenresRecord> booksBooksGenreIdFkey, Object parentPath) {

        }

        @Override
        public GenresPath as(String alias) {
            return new GenresPath(DSL.name(alias), this);
        }

        @Override
        public GenresPath as(Name alias) {
            return new GenresPath(alias, this);
        }

        @Override
        public GenresPath as(Table<?> alias) {
            return new GenresPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<GenresRecord, Long> getIdentity() {
        return (Identity<GenresRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<GenresRecord> getPrimaryKey() {
        return Keys.GENRES_PKEY;
    }

    @Override
    public List<UniqueKey<GenresRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.GENRES_NAME_KEY);
    }

    private transient BooksPath _books;

    /**
     * Get the implicit to-many join path to the <code>public.books</code> table
     */
    public BooksPath books() {
        if (_books == null)
            _books = new BooksPath(this, null, Keys.BOOKS__BOOKS_GENRE_ID_FKEY.getInverseKey());

        return _books;
    }

    @Override
    public Genres as(String alias) {
        return new Genres(DSL.name(alias), this);
    }

    @Override
    public Genres as(Name alias) {
        return new Genres(alias, this);
    }

    @Override
    public Genres as(Table<?> alias) {
        return new Genres(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Genres rename(String name) {
        return new Genres(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Genres rename(Name name) {
        return new Genres(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Genres rename(Table<?> name) {
        return new Genres(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Genres where(Condition condition) {
        return new Genres(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Genres where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Genres where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Genres where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Genres where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Genres where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Genres where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Genres where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Genres whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Genres whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
