/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.tables;


import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import com.example.jooq.Indexes;
import com.example.jooq.Keys;
import com.example.jooq.Public;
import com.example.jooq.tables.Borrowings.BorrowingsPath;
import com.example.jooq.tables.records.BorrowingsRecord;
import com.example.jooq.tables.records.ReadersRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Readers extends TableImpl<ReadersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.readers</code>
     */
    public static final Readers READERS = new Readers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReadersRecord> getRecordType() {
        return ReadersRecord.class;
    }

    /**
     * The column <code>public.readers.id</code>.
     */
    public final TableField<ReadersRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.readers.name</code>.
     */
    public final TableField<ReadersRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.readers.email</code>.
     */
    public final TableField<ReadersRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.readers.phone</code>.
     */
    public final TableField<ReadersRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.readers.membership_date</code>.
     */
    public final TableField<ReadersRecord, LocalDate> MEMBERSHIP_DATE = createField(DSL.name("membership_date"), SQLDataType.LOCALDATE.defaultValue(DSL.field(DSL.raw("CURRENT_DATE"), SQLDataType.LOCALDATE)), this, "");

    /**
     * The column <code>public.readers.is_active</code>.
     */
    public final TableField<ReadersRecord, Boolean> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    private Readers(Name alias, Table<ReadersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Readers(Name alias, Table<ReadersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.readers</code> table reference
     */
    public Readers(String alias) {
        this(DSL.name(alias), READERS);
    }

    /**
     * Create an aliased <code>public.readers</code> table reference
     */
    public Readers(Name alias) {
        this(alias, READERS);
    }

    /**
     * Create a <code>public.readers</code> table reference
     */
    public Readers() {
        this(DSL.name("readers"), null);
    }

    public <O extends Record> Readers(Table<O> path, ForeignKey<O, ReadersRecord> childPath, InverseForeignKey<O, ReadersRecord> parentPath) {
        super(path, childPath, parentPath, READERS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReadersPath extends Readers implements Path<ReadersRecord> {

        private static final long serialVersionUID = 1L;

        public <O extends Record> ReadersPath(Table<O> path, ForeignKey<O, ReadersRecord> childPath, InverseForeignKey<O, ReadersRecord> parentPath) {
            super(path, childPath, parentPath);
        }

        private ReadersPath(Name alias, Table<ReadersRecord> aliased) {
            super(alias, aliased);
        }

        public ReadersPath(Borrowings borrowings, ForeignKey<BorrowingsRecord, ReadersRecord> borrowingsBorrowingsReaderIdFkey, Object parentPath) {
        }

        @Override
        public ReadersPath as(String alias) {
            return new ReadersPath(DSL.name(alias), this);
        }

        @Override
        public ReadersPath as(Name alias) {
            return new ReadersPath(alias, this);
        }

        @Override
        public ReadersPath as(Table<?> alias) {
            return new ReadersPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_READERS_EMAIL);
    }

    @Override
    public Identity<ReadersRecord, Long> getIdentity() {
        return (Identity<ReadersRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReadersRecord> getPrimaryKey() {
        return Keys.READERS_PKEY;
    }

    @Override
    public List<UniqueKey<ReadersRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.READERS_EMAIL_KEY);
    }

    private transient BorrowingsPath _borrowings;

    /**
     * Get the implicit to-many join path to the <code>public.borrowings</code>
     * table
     */
    public BorrowingsPath borrowings() {
        if (_borrowings == null)
            _borrowings = new BorrowingsPath(this, null, Keys.BORROWINGS__BORROWINGS_READER_ID_FKEY.getInverseKey());

        return _borrowings;
    }

    @Override
    public Readers as(String alias) {
        return new Readers(DSL.name(alias), this);
    }

    @Override
    public Readers as(Name alias) {
        return new Readers(alias, this);
    }

    @Override
    public Readers as(Table<?> alias) {
        return new Readers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Readers rename(String name) {
        return new Readers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Readers rename(Name name) {
        return new Readers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Readers rename(Table<?> name) {
        return new Readers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Readers where(Condition condition) {
        return new Readers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Readers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Readers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Readers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Readers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Readers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Readers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Readers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Readers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Readers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
